export const actionType = {
    ABOUTLOADDATA: 'ABOUTLOADDATA',
    ABOUTLISTADD: 'ABOUTLISTADD',
    ABOUTLISTDEL: 'ABOUTLISTDEL',
    ABOUTLISTSHOW: 'ABOUTLISTSHOW',

    HOMELISTADD: 'HOMELISTADD',
    HOMELISTDEL: 'HOMELISTDEL',
    HOMELISTMODIFY: 'HOMELISTMODIFY',
    HOMELISTFIND: 'HOMELISTFIND',

    HOMELISTSHOW: 'HOMELISTSHOW',
    HOMELOADDATA: 'HOMELOADDATA',
    HOMECLEARDATA: 'HOMECLEARDATA',

    LOGIN:'LOGIN',
    LOGOUT:'LOGOUT',
    SAVESTATE:'SAVESTATE',
    LOGINSUC:'LOGINSUC',

};
